"""nova-executor Python SDK"""

from .client import ExecutorClient
from .config import (
    NOVA_EXECUTOR_HOME_ENV,
    ApprovalPolicy,
    ExecutorConfig,
    NetworkProxySettings,
    SandboxMode,
    SandboxWorkspaceWriteConfig,
    default_executor_home,
    load_executor_config,
)
from .errors import (
    EXECUTOR_NOT_FOUND,
    JSON_RPC_INTERNAL_ERROR,
    JSON_RPC_INVALID_PARAMS,
    JSON_RPC_INVALID_REQUEST,
    JSON_RPC_METHOD_NOT_FOUND,
    SESSION_ALREADY_ATTACHED,
    AuthError,
    ConfigError,
    ConnectionError,
    ExecutorError,
    FileSystemError,
    ProcessError,
    ProtocolError,
    TimeoutError,
    TransportError,
)
from .fs import FileSystemManager
from .gate import AskOutcome, NetworkPolicyGate
from .notifications import NotificationRouter, ReadStreamEvent
from .policy import (
    ResolvedExecutionPolicy,
    resolve_ask_behavior,
    resolve_execution_policy,
    resolve_file_system_sandbox,
    resolve_network_proxy,
)
from .pool import CHANNEL_CONTROL, CHANNEL_DATA, DATA_CHANNEL_METHODS, TransportPool
from .process import ProcessHandle, ProcessManager, ProcessOutput
from .protocol import (
    NETWORK_POLICY_DECISION,
    NETWORK_POLICY_REQUEST,
    EnvironmentCapabilities,
    EnvironmentConfigLayer,
    EnvironmentConfigLayerStack,
    EnvironmentConfigReadParams,
    EnvironmentConfigReadResponse,
    EnvironmentInfo,
    EnvironmentStatus,
    ExecEnvPolicy,
    ExecFileSystemPath,
    ExecFileSystemSandboxEntry,
    ExecFileSystemSpecialPath,
    ExecManagedFileSystemPermissions,
    ExecPermissionProfile,
    ExecServerNetworkPolicyRequest,
    ExecServerNetworkProtocol,
    FileSystemAccessMode,
    FileSystemSandboxContext,
    HttpHeader,
    HttpRedirectPolicy,
    HttpRequestParams,
    HttpRequestResponse,
    ManagedNetworkSandboxContext,
    NetworkDomainPermission,
    NetworkDomainPermissionEntry,
    NetworkDomainPermissions,
    NetworkMode,
    NetworkPolicyDecision,
    NetworkPolicyDecisionNotification,
    NetworkPolicyRequestParams,
    NetworkPolicyRequestResponse,
    NetworkProxyAuditMetadata,
    NetworkSandboxPolicy,
    RemoteNetworkProxyConfig,
    RemoteNetworkProxyLaunchConfig,
    ShellSnapshotRequest,
    WindowsSandboxLevel,
    WindowsSandboxProxySettingsMode,
)
from .pty import PtyHandle, PtyManager
from .recovery import ManagedTransport, ReconnectStrategy
from .transport import StdioTransport, Transport, WebSocketTransport

__all__ = [
    "ExecutorClient",
    "ExecutorError",
    "ConnectionError",
    "TransportError",
    "AuthError",
    "ConfigError",
    "ProcessError",
    "FileSystemError",
    "ProtocolError",
    "TimeoutError",
    "ProcessManager",
    "ProcessHandle",
    "ProcessOutput",
    "FileSystemManager",
    "PtyManager",
    "PtyHandle",
    "Transport",
    "WebSocketTransport",
    "StdioTransport",
    "TransportPool",
    "CHANNEL_CONTROL",
    "CHANNEL_DATA",
    "DATA_CHANNEL_METHODS",
    "ReconnectStrategy",
    "ManagedTransport",
    "NotificationRouter",
    "ReadStreamEvent",
    # 协议模型（沙箱/HTTP/环境元数据）
    "FileSystemSandboxContext",
    "ExecPermissionProfile",
    "ExecManagedFileSystemPermissions",
    "ExecFileSystemSandboxEntry",
    "ExecFileSystemPath",
    "ExecFileSystemSpecialPath",
    "ExecEnvPolicy",
    "ShellSnapshotRequest",
    "ManagedNetworkSandboxContext",
    "NetworkSandboxPolicy",
    "FileSystemAccessMode",
    "WindowsSandboxLevel",
    "WindowsSandboxProxySettingsMode",
    "HttpRequestParams",
    "HttpRequestResponse",
    "HttpHeader",
    "HttpRedirectPolicy",
    "EnvironmentInfo",
    "EnvironmentStatus",
    "EnvironmentCapabilities",
    "EnvironmentConfigReadParams",
    "EnvironmentConfigReadResponse",
    "EnvironmentConfigLayer",
    "EnvironmentConfigLayerStack",
    # 网络策略（托管网络沙箱裁决）
    "NetworkPolicyDecision",
    "NetworkPolicyDecisionNotification",
    "NetworkPolicyRequestParams",
    "NetworkPolicyRequestResponse",
    "ExecServerNetworkProtocol",
    "ExecServerNetworkPolicyRequest",
    # 托管网络代理启动配置（wire 类型族）
    "NetworkMode",
    "NetworkDomainPermission",
    "NetworkDomainPermissionEntry",
    "NetworkDomainPermissions",
    "NetworkProxyAuditMetadata",
    "RemoteNetworkProxyConfig",
    "RemoteNetworkProxyLaunchConfig",
    "NETWORK_POLICY_REQUEST",
    "NETWORK_POLICY_DECISION",
    # executor 配置根（发现+物化——执行词汇归 executor 栈自持）
    "load_executor_config",
    "default_executor_home",
    "ExecutorConfig",
    "SandboxMode",
    "SandboxWorkspaceWriteConfig",
    "NetworkProxySettings",
    "ApprovalPolicy",
    "NOVA_EXECUTOR_HOME_ENV",
    "resolve_execution_policy",
    "resolve_file_system_sandbox",
    "resolve_network_proxy",
    "resolve_ask_behavior",
    "ResolvedExecutionPolicy",
    # 网络裁决门（policyRequest 回调底座：会话记忆 + ask 注入 + fail-closed）
    "NetworkPolicyGate",
    "AskOutcome",
    "JSON_RPC_INVALID_REQUEST",
    "JSON_RPC_METHOD_NOT_FOUND",
    "JSON_RPC_INVALID_PARAMS",
    "JSON_RPC_INTERNAL_ERROR",
    "EXECUTOR_NOT_FOUND",
    "SESSION_ALREADY_ATTACHED",
]
