"""nova-executor Python SDK"""

from .client import ExecutorClient
from .errors import (
    EXECUTOR_NOT_FOUND,
    JSON_RPC_INTERNAL_ERROR,
    JSON_RPC_INVALID_PARAMS,
    JSON_RPC_INVALID_REQUEST,
    JSON_RPC_METHOD_NOT_FOUND,
    SESSION_ALREADY_ATTACHED,
    AuthError,
    ConnectionError,
    ExecutorError,
    FileSystemError,
    ProcessError,
    ProtocolError,
    TimeoutError,
    TransportError,
)
from .fs import FileSystemManager
from .notifications import NotificationRouter, ReadStreamEvent
from .pool import CHANNEL_CONTROL, CHANNEL_DATA, DATA_CHANNEL_METHODS, TransportPool
from .process import ProcessHandle, ProcessManager, ProcessOutput
from .protocol import (
    NETWORK_POLICY_DECISION,
    NETWORK_POLICY_REQUEST,
    EnvironmentCapabilities,
    EnvironmentConfigLayer,
    EnvironmentConfigLayerStack,
    EnvironmentConfigReadParams,
    EnvironmentConfigReadResponse,
    EnvironmentInfo,
    EnvironmentStatus,
    ExecEnvPolicy,
    ExecFileSystemPath,
    ExecFileSystemSandboxEntry,
    ExecManagedFileSystemPermissions,
    ExecPermissionProfile,
    ExecServerNetworkPolicyRequest,
    ExecServerNetworkProtocol,
    FileSystemAccessMode,
    FileSystemSandboxContext,
    HttpHeader,
    HttpRedirectPolicy,
    HttpRequestParams,
    HttpRequestResponse,
    ManagedNetworkSandboxContext,
    NetworkPolicyDecision,
    NetworkPolicyRequestParams,
    NetworkPolicyRequestResponse,
    NetworkSandboxPolicy,
    ShellSnapshotRequest,
    WindowsSandboxLevel,
    WindowsSandboxProxySettingsMode,
)
from .pty import PtyHandle, PtyManager
from .recovery import ManagedTransport, ReconnectStrategy
from .transport import StdioTransport, Transport, WebSocketTransport

__all__ = [
    "ExecutorClient",
    "ExecutorError",
    "ConnectionError",
    "TransportError",
    "AuthError",
    "ProcessError",
    "FileSystemError",
    "ProtocolError",
    "TimeoutError",
    "ProcessManager",
    "ProcessHandle",
    "ProcessOutput",
    "FileSystemManager",
    "PtyManager",
    "PtyHandle",
    "Transport",
    "WebSocketTransport",
    "StdioTransport",
    "TransportPool",
    "CHANNEL_CONTROL",
    "CHANNEL_DATA",
    "DATA_CHANNEL_METHODS",
    "ReconnectStrategy",
    "ManagedTransport",
    "NotificationRouter",
    "ReadStreamEvent",
    # 协议模型（沙箱/HTTP/环境元数据）
    "FileSystemSandboxContext",
    "ExecPermissionProfile",
    "ExecManagedFileSystemPermissions",
    "ExecFileSystemSandboxEntry",
    "ExecFileSystemPath",
    "ExecEnvPolicy",
    "ShellSnapshotRequest",
    "ManagedNetworkSandboxContext",
    "NetworkSandboxPolicy",
    "FileSystemAccessMode",
    "WindowsSandboxLevel",
    "WindowsSandboxProxySettingsMode",
    "HttpRequestParams",
    "HttpRequestResponse",
    "HttpHeader",
    "HttpRedirectPolicy",
    "EnvironmentInfo",
    "EnvironmentStatus",
    "EnvironmentCapabilities",
    "EnvironmentConfigReadParams",
    "EnvironmentConfigReadResponse",
    "EnvironmentConfigLayer",
    "EnvironmentConfigLayerStack",
    # 网络策略（托管网络沙箱裁决）
    "NetworkPolicyDecision",
    "NetworkPolicyRequestParams",
    "NetworkPolicyRequestResponse",
    "ExecServerNetworkProtocol",
    "ExecServerNetworkPolicyRequest",
    "NETWORK_POLICY_REQUEST",
    "NETWORK_POLICY_DECISION",
    "JSON_RPC_INVALID_REQUEST",
    "JSON_RPC_METHOD_NOT_FOUND",
    "JSON_RPC_INVALID_PARAMS",
    "JSON_RPC_INTERNAL_ERROR",
    "EXECUTOR_NOT_FOUND",
    "SESSION_ALREADY_ATTACHED",
]
