"""
事件 payload 与结果类型。

集中存放原 `nova_harness.extensions.types` 中的事件类型、
原 `nova_harness.agent.events` 中的 AgentSession 事件，以及所有事件结果类型。
所有事件统一使用 dataclass，避免不可序列化对象触发 Pydantic 校验。

模块已按职责拆分为：
- `constants`：事件类型常量
- `auto`：AgentSession 自动触发的内部事件
- `session`：会话生命周期事件
- `agent`：Agent / turn / message / tool / 其他事件
- `results`：事件结果类型
- `unions`：事件联合类型与监听器类型
"""

from .agent import (
    AfterProviderResponseEvent,
    AgentEndEvent,
    AgentSettledEvent,
    AgentStartEvent,
    BeforeAgentStartEvent,
    BeforeProviderHeadersEvent,
    BeforeProviderRequestEvent,
    ContextEvent,
    ExtensionErrorEvent,
    InputEvent,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    ModelSelectEvent,
    PrepareNextTurnEvent,
    ResourcesDiscoverEvent,
    ShouldStopAfterTurnEvent,
    ThinkingLevelSelectEvent,
    ToolCallEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    ToolResultEvent,
    TurnEndEvent,
    TurnStartEvent,
    UserBashEvent,
)
from .auto import (
    AutoCompactionEndEvent,
    AutoCompactionReason,
    AutoCompactionStartEvent,
    AutoRetryEndEvent,
    AutoRetryStartEvent,
    ItemEmissionEvent,
    ModelChangedEvent,
    QueueUpdateEvent,
    SessionInfoChangedEvent,
    SessionReloadedEvent,
    SessionReplacedEvent,
    ThinkingLevelChangedEvent,
)
from .constants import (
    AFTER_PROVIDER_RESPONSE,
    AGENT_END,
    AGENT_SETTLED,
    AGENT_START,
    AUTO_COMPACTION_END,
    AUTO_COMPACTION_START,
    AUTO_RETRY_END,
    AUTO_RETRY_START,
    BEFORE_AGENT_START,
    BEFORE_PROVIDER_HEADERS,
    BEFORE_PROVIDER_REQUEST,
    COMPACTION_END,
    COMPACTION_START,
    CONTEXT,
    EXTENSION_ERROR,
    INPUT,
    ITEM_EMISSION,
    MESSAGE_END,
    MESSAGE_START,
    MESSAGE_UPDATE,
    MODEL_SELECT,
    PREPARE_NEXT_TURN,
    QUEUE_UPDATE,
    RESOURCES_DISCOVER,
    SESSION_BEFORE_COMPACT,
    SESSION_BEFORE_FORK,
    SESSION_BEFORE_SWITCH,
    SESSION_BEFORE_TREE,
    SESSION_COMPACT,
    SESSION_INFO_CHANGED,
    SESSION_RELOADED,
    SESSION_REPLACED,
    SESSION_SHUTDOWN,
    SESSION_START,
    SESSION_TREE,
    SHOULD_STOP_AFTER_TURN,
    THINKING_LEVEL_CHANGED,
    THINKING_LEVEL_SELECT,
    TOOL_CALL,
    TOOL_EXECUTION_END,
    TOOL_EXECUTION_START,
    TOOL_EXECUTION_UPDATE,
    TOOL_RESULT,
    TURN_END,
    TURN_START,
    USER_BASH,
)
from .results import (
    BeforeAgentStartEventResult,
    BeforeProviderRequestEventResult,
    ContextEventResult,
    InputEventResult,
    MessageEndEventResult,
    PrepareNextTurnEventResult,
    ResourcesDiscoverEventResult,
    SessionBeforeCompactResult,
    SessionBeforeForkResult,
    SessionBeforeSwitchResult,
    SessionBeforeTreeResult,
    ShouldStopAfterTurnEventResult,
    ToolCallEventResult,
    ToolResultEventResult,
    UserBashEventResult,
)
from .session import (
    CacheMissEvent,
    CompactionEndEvent,
    CompactionStartEvent,
    EntryAppendedEvent,
    SessionBeforeCompactEvent,
    SessionBeforeForkEvent,
    SessionBeforeSwitchEvent,
    SessionBeforeTreeEvent,
    SessionCompactEvent,
    SessionShutdownEvent,
    SessionStartEvent,
    SessionTreeEvent,
    TreePreparation,
)
from .unions import (
    AgentSessionEvent,
    AgentSessionEventListener,
    ExtensionEvent,
    ExtensionEventHandler,
    ExtensionEventResult,
)

__all__ = [
    # constants
    "SESSION_START",
    "SESSION_SHUTDOWN",
    "SESSION_BEFORE_SWITCH",
    "SESSION_BEFORE_FORK",
    "SESSION_BEFORE_COMPACT",
    "SESSION_COMPACT",
    "SESSION_BEFORE_TREE",
    "SESSION_TREE",
    "COMPACTION_START",
    "COMPACTION_END",
    "CONTEXT",
    "BEFORE_PROVIDER_HEADERS",
    "BEFORE_PROVIDER_REQUEST",
    "AFTER_PROVIDER_RESPONSE",
    "BEFORE_AGENT_START",
    "AGENT_START",
    "AGENT_END",
    "AGENT_SETTLED",
    "TURN_START",
    "TURN_END",
    "MESSAGE_START",
    "MESSAGE_UPDATE",
    "MESSAGE_END",
    "TOOL_EXECUTION_START",
    "TOOL_EXECUTION_UPDATE",
    "TOOL_EXECUTION_END",
    "TOOL_CALL",
    "TOOL_RESULT",
    "USER_BASH",
    "INPUT",
    "MODEL_SELECT",
    "THINKING_LEVEL_SELECT",
    "RESOURCES_DISCOVER",
    "PREPARE_NEXT_TURN",
    "SHOULD_STOP_AFTER_TURN",
    "AUTO_COMPACTION_START",
    "AUTO_COMPACTION_END",
    "AUTO_RETRY_START",
    "AUTO_RETRY_END",
    "QUEUE_UPDATE",
    "SESSION_INFO_CHANGED",
    "SESSION_RELOADED",
    "SESSION_REPLACED",
    "THINKING_LEVEL_CHANGED",
    "EXTENSION_ERROR",
    "ITEM_EMISSION",
    # 包级 item 发射信封（内部总线专用，不上线）
    "ItemEmissionEvent",
    # agent session events
    "AutoCompactionReason",
    "AutoCompactionStartEvent",
    "AutoCompactionEndEvent",
    "AutoRetryStartEvent",
    "AutoRetryEndEvent",
    "ModelChangedEvent",
    "QueueUpdateEvent",
    "SessionInfoChangedEvent",
    "SessionReloadedEvent",
    "SessionReplacedEvent",
    "ThinkingLevelChangedEvent",
    "AgentSessionEvent",
    "AgentSessionEventListener",
    # session lifecycle events
    "SessionStartEvent",
    "SessionShutdownEvent",
    "SessionBeforeSwitchEvent",
    "SessionBeforeForkEvent",
    "SessionBeforeCompactEvent",
    "SessionCompactEvent",
    "CompactionStartEvent",
    "CompactionEndEvent",
    "TreePreparation",
    "SessionBeforeTreeEvent",
    "SessionTreeEvent",
    "EntryAppendedEvent",
    "CacheMissEvent",
    # agent/turn/message/tool/other events
    "ContextEvent",
    "BeforeProviderHeadersEvent",
    "BeforeProviderRequestEvent",
    "AfterProviderResponseEvent",
    "BeforeAgentStartEvent",
    "AgentStartEvent",
    "AgentEndEvent",
    "AgentSettledEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "PrepareNextTurnEvent",
    "ShouldStopAfterTurnEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "MessageEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolExecutionEndEvent",
    "ToolCallEvent",
    "ToolResultEvent",
    "UserBashEvent",
    "InputEvent",
    "ModelSelectEvent",
    "ThinkingLevelSelectEvent",
    "ResourcesDiscoverEvent",
    # result types
    "ContextEventResult",
    "ToolCallEventResult",
    "ToolResultEventResult",
    "MessageEndEventResult",
    "BeforeAgentStartEventResult",
    "BeforeProviderRequestEventResult",
    "SessionBeforeSwitchResult",
    "SessionBeforeForkResult",
    "SessionBeforeCompactResult",
    "SessionBeforeTreeResult",
    "UserBashEventResult",
    "InputEventResult",
    "ResourcesDiscoverEventResult",
    "PrepareNextTurnEventResult",
    "ShouldStopAfterTurnEventResult",
    # error / unions
    "ExtensionErrorEvent",
    "ExtensionEvent",
    "ExtensionEventResult",
    "ExtensionEventHandler",
]
