# This file is auto-generated by scripts/generate_models.py
# Do not edit manually - run 'pixi run -e dev generate-models' to update

"""生成的模型目录聚合器（对齐 TS ``src/models.generated.ts``）。"""

from nova_ai.providers.kimi_coding.models import KIMI_CODING_MODELS
from nova_ai.providers.moonshotai.models import MOONSHOTAI_MODELS
from nova_ai.providers.moonshotai_cn.models import MOONSHOTAI_CN_MODELS
from nova_ai.providers.volcengine.models import VOLCENGINE_MODELS

PROVIDER_IDS = ['kimi-coding', 'moonshotai', 'moonshotai-cn', 'volcengine']

GENERATED_PROVIDER_MODELS = {
    "kimi-coding": KIMI_CODING_MODELS,
    "moonshotai": MOONSHOTAI_MODELS,
    "moonshotai-cn": MOONSHOTAI_CN_MODELS,
    "volcengine": VOLCENGINE_MODELS
}
