# This file is auto-generated by scripts/generate_models.py
# Do not edit manually - run 'pixi run -e dev generate-models' to update

"""Kimi Coding 模型目录（生成 shard）。"""

import json
from pathlib import Path
from typing import Dict

from nova_ai.model_catalog import flatten_model_catalog
from nova_ai.types.model import Model

KIMI_CODING_BASE_URL = "https://api.kimi.com/coding/v1"

KIMI_CODING_MODELS: Dict[str, Model] = flatten_model_catalog(
    "kimi-coding",
    json.loads(
        (Path(__file__).resolve().parent.parent / "data" / "kimi-coding.json").read_text(
            "utf-8"
        )
    ),
)


def get_kimi_coding_model(model_id: str) -> Model:
    """通过 ID 获取 Kimi Coding 模型。"""
    if model_id not in KIMI_CODING_MODELS:
        raise KeyError(f"Kimi Coding model not found: {model_id}")
    return KIMI_CODING_MODELS[model_id]


def list_kimi_coding_models() -> Dict[str, Model]:
    """列出所有 Kimi Coding 模型。"""
    return KIMI_CODING_MODELS.copy()
