#!/usr/bin/env python3
"""模型目录种子生成器（对齐 TS ``scripts/generate-models.ts``）。

数据源映射与修正层单源住在 ``nova_ai.providers.catalog``（运行时物化
``providers/remote_catalog.py`` 与本脚本共用同一份映射代码）；本脚本只负责
**发射构建期种子**：数据分片（``providers/data/<id>.json``）、生成 shard
（``providers/<module>/models.py``）、聚合器（``models_generated.py``）与
manifest（schemaVersion + generatedAt + 结构/文件哈希）。

种子是冷启动/离线兜底与测试 fixture；运行时的新鲜数据由
``remote_catalog.with_remote_catalog`` 物化到 ``~/.nova/agent/models-store.json``。

用法::

    pixi run -e dev generate-models                 # 重新生成种子
    pixi run -e dev generate-models --data-only     # 只重写数据分片与 manifest
    pixi run -e dev generate-models --strict        # 数据源异常即抛
    pixi run -e dev check-model-data                # 保鲜检查（漂移即红）
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict

PACKAGE_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PACKAGE_ROOT / "scripts"))

import model_data as mdata  # noqa: E402

from nova_ai.providers.catalog import (  # noqa: E402
    API,
    PROVIDERS,
    build_provider_models,
    fetch_ark_status,
    fetch_models_dev,
    source_models_for,
)

_SHARD_TEMPLATE = '''\
# This file is auto-generated by scripts/generate_models.py
# Do not edit manually - run 'pixi run -e dev generate-models' to update

"""{label} 模型目录（生成 shard）。"""

import json
from pathlib import Path
from typing import Dict

from nova_ai.model_catalog import flatten_model_catalog
from nova_ai.types.model import Model

{prefix}_BASE_URL = "{base_url}"

{prefix}_MODELS: Dict[str, Model] = flatten_model_catalog(
    "{provider_id}",
    json.loads(
        (Path(__file__).resolve().parent.parent / "data" / "{provider_id}.json").read_text(
            "utf-8"
        )
    ),
)


def get_{module}_model(model_id: str) -> Model:
    """通过 ID 获取 {label} 模型。"""
    if model_id not in {prefix}_MODELS:
        raise KeyError(f"{label} model not found: {{model_id}}")
    return {prefix}_MODELS[model_id]


def list_{module}_models() -> Dict[str, Model]:
    """列出所有 {label} 模型。"""
    return {prefix}_MODELS.copy()
'''

_AGGREGATOR_TEMPLATE = '''\
# This file is auto-generated by scripts/generate_models.py
# Do not edit manually - run 'pixi run -e dev generate-models' to update

"""生成的模型目录聚合器（对齐 TS ``src/models.generated.ts``）。"""

{imports}

PROVIDER_IDS = {provider_ids}

GENERATED_PROVIDER_MODELS = {{
{entries}
}}
'''


def _write_if_changed(path: Path, content: str) -> bool:
    old = path.read_text("utf-8") if path.exists() else None
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, "utf-8")
    return old != content


def main(argv: Any = None) -> int:
    parser = argparse.ArgumentParser(description="生成 nova_ai 模型目录种子")
    parser.add_argument(
        "--strict", action="store_true", help="数据源异常时抛错（build 用）"
    )
    parser.add_argument(
        "--data-only", action="store_true", help="只重写数据分片与 manifest"
    )
    parser.add_argument("--pretty", action="store_true", help="数据分片缩进输出")
    args = parser.parse_args(argv)

    print("Fetching models from models.dev API...")
    models_dev = fetch_models_dev()
    ark_status = fetch_ark_status(os.environ.get("VOLCENGINE_API_KEY"))
    if ark_status:
        print(f"Ark liveness: {len(ark_status)} retired/retiring models")
    else:
        print("Ark liveness skipped (no VOLCENGINE_API_KEY)")

    # ---- 逐 provider 组装字段 ----
    built: Dict[str, Dict[str, Dict[str, Any]]] = {}
    for provider_id in PROVIDERS:
        raw = source_models_for(provider_id)
        built[provider_id] = build_provider_models(
            provider_id,
            raw,
            strict=args.strict,
            static=provider_id == "kimi-coding",
            ark_status=ark_status if provider_id == "volcengine" else None,
        )
        dropped = len(raw) - len(built[provider_id])
        print(
            f"{provider_id}: {len(built[provider_id])} models"
            + (f"（源 {len(raw)}，过滤/钉住净变动 {dropped}）" if dropped else "")
        )

    # ---- 写数据分片 ----
    data_dir = PACKAGE_ROOT / "src" / "nova_ai" / "providers" / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    indent = 2 if args.pretty else None
    file_contents: Dict[str, str] = {}
    for provider_id in PROVIDERS:
        groups = {API: dict(sorted(built[provider_id].items()))}
        content = json.dumps(groups, ensure_ascii=False, indent=indent, sort_keys=True)
        filename = f"{provider_id}.json"
        (data_dir / filename).write_text(content + "\n", "utf-8")
        file_contents[filename] = content + "\n"

    # ---- manifest ----
    structure = {pid: {mid: API for mid in models} for pid, models in built.items()}
    manifest = mdata.create_model_data_manifest(
        structure,
        file_contents,
        datetime.now(timezone.utc).isoformat(timespec="seconds"),
    )
    (data_dir / mdata.MODEL_DATA_MANIFEST_FILE).write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        "utf-8",
    )
    print(f"wrote {len(file_contents)} data shards + manifest")

    if args.data_only:
        print("data-only: shards/aggregator untouched")
        return 0

    # ---- 生成 shard 与聚合器 ----
    rewritten = 0
    for provider_id, constants in PROVIDERS.items():
        shard = _SHARD_TEMPLATE.format(
            label=constants["label"],
            prefix=constants["prefix"],
            base_url=constants["base_url"],
            provider_id=provider_id,
            module=constants["module"],
        )
        shard_path = (
            PACKAGE_ROOT
            / "src"
            / "nova_ai"
            / "providers"
            / constants["module"]
            / "models.py"
        )
        if _write_if_changed(shard_path, shard):
            rewritten += 1

    imports = "\n".join(
        f"from nova_ai.providers.{c['module']}.models import {c['prefix']}_MODELS"
        for c in PROVIDERS.values()
    )
    entries = ",\n".join(
        f'    "{pid}": {c["prefix"]}_MODELS' for pid, c in PROVIDERS.items()
    )
    aggregator = _AGGREGATOR_TEMPLATE.format(
        imports=imports,
        provider_ids=repr(sorted(PROVIDERS)),
        entries=entries,
    )
    if _write_if_changed(
        PACKAGE_ROOT / "src" / "nova_ai" / "models_generated.py", aggregator
    ):
        rewritten += 1
    print(f"rewrote {rewritten} generated files")

    # ---- 自校验：生成即验收 ----
    mdata.validate_generated_model_data(PACKAGE_ROOT)
    print("Generated model data is valid.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
