# This file is auto-generated by scripts/generate_models.py
# Do not edit manually - run 'pixi run -e dev generate-models' to update

"""Moonshot AI CN 模型目录（生成 shard）。"""

import json
from pathlib import Path
from typing import Dict

from nova_ai.model_catalog import flatten_model_catalog
from nova_ai.types.model import Model

MOONSHOTAI_CN_BASE_URL = "https://api.moonshot.cn/v1"

MOONSHOTAI_CN_MODELS: Dict[str, Model] = flatten_model_catalog(
    "moonshotai-cn",
    json.loads(
        (Path(__file__).resolve().parent.parent / "data" / "moonshotai-cn.json").read_text(
            "utf-8"
        )
    ),
)


def get_moonshotai_cn_model(model_id: str) -> Model:
    """通过 ID 获取 Moonshot AI CN 模型。"""
    if model_id not in MOONSHOTAI_CN_MODELS:
        raise KeyError(f"Moonshot AI CN model not found: {model_id}")
    return MOONSHOTAI_CN_MODELS[model_id]


def list_moonshotai_cn_models() -> Dict[str, Model]:
    """列出所有 Moonshot AI CN 模型。"""
    return MOONSHOTAI_CN_MODELS.copy()
