"""nova_protocol —— Nova 词汇枢纽。

跨组件边界的全部纯数据形状（零行为、零兄弟包依赖）。收录标准、三纪律与
序列化出口约定见包 README。

消费方一律 ``from nova_protocol import X``（本模块全量门面再导出，
内部文件布局自由）。
"""

from .agent_events import (
    AgentEndEvent,
    AgentEvent,
    AgentMessage,
    AgentStartEvent,
    AgentToolResult,
    CustomAgentMessage,
    MessageEndEvent,
    MessageStartEvent,
    MessageUpdateEvent,
    ToolExecutionEndEvent,
    ToolExecutionStartEvent,
    ToolExecutionUpdateEvent,
    TurnEndEvent,
    TurnStartEvent,
    dump_agent_message,
)
from .aliases import ProviderEnv, ProviderHeaders
from .auth import (
    ApiKeyAuth,
    ApiKeyAuthInput,
    ApiKeyCredential,
    AuthCheck,
    AuthContext,
    AuthEvent,
    AuthInfoLink,
    AuthInteraction,
    AuthorizationRequest,
    AuthPrompt,
    AuthPromptOption,
    AuthResult,
    AuthType,
    Credential,
    CredentialInfo,
    CredentialStore,
    LoginCancelledError,
    ModelAuth,
    OAuthAuth,
    OAuthCredential,
    ProviderAuth,
)
from .base_model import NovaBaseModel
from .compat import (
    AnthropicMessagesCompat,
    DeferredToolsMode,
    OpenAICompletionsCompat,
    OpenAIResponsesCompat,
    OpenRouterRouting,
    SessionAffinityFormat,
    VercelGatewayRouting,
)
from .content import ContentUnion, ImageContent, TextContent, ThinkingContent, ToolCall
from .enums import (
    Api,
    CacheRetention,
    KnownApi,
    KnownProvider,
    ModelThinkingLevel,
    ProviderId,
    StopReason,
    ThinkingFormat,
    ThinkingLevel,
    ThinkingLevelMap,
    ThinkingTokenBudgetField,
    Transport,
)
from .events import (
    AssistantMessageEvent,
    DoneEvent,
    ErrorEvent,
    StartEvent,
    TextDeltaEvent,
    TextEndEvent,
    TextStartEvent,
    ThinkingDeltaEvent,
    ThinkingEndEvent,
    ThinkingStartEvent,
    ToolCallDeltaEvent,
    ToolCallEndEvent,
    ToolCallStartEvent,
)
from .ids import EntryId, RunId, SessionId, ToolCallId
from .messages import (
    AssistantMessage,
    Context,
    Message,
    Tool,
    ToolResultMessage,
    UserMessage,
)
from .model import (
    Cost,
    Model,
    ModelCost,
    ModelCostRates,
    ModelCostTier,
    ModelsStoreEntry,
    Usage,
)
from .signal import AbortController, AbortedError, AbortSignal, is_aborted

__all__ = [
    # 基类
    "NovaBaseModel",
    # 语义 id
    "SessionId",
    "EntryId",
    "RunId",
    "ToolCallId",
    # 取消原语
    "AbortController",
    "AbortSignal",
    "AbortedError",
    "is_aborted",
    # 枚举
    "Api",
    "KnownApi",
    "ProviderId",
    "KnownProvider",
    "StopReason",
    "ThinkingLevel",
    "ModelThinkingLevel",
    "CacheRetention",
    "Transport",
    "ThinkingFormat",
    "ThinkingLevelMap",
    "ThinkingTokenBudgetField",
    # 内容类型
    "TextContent",
    "ThinkingContent",
    "ToolCall",
    "ImageContent",
    "ContentUnion",
    # 使用统计
    "Usage",
    "Cost",
    # 模型类型
    "Model",
    "ModelCost",
    "ModelCostRates",
    "ModelCostTier",
    "ModelsStoreEntry",
    # 消息类型
    "AssistantMessage",
    "UserMessage",
    "ToolResultMessage",
    "Message",
    "Tool",
    "Context",
    # Agent 消息与事件（批次 ②）
    "CustomAgentMessage",
    "AgentMessage",
    "AgentToolResult",
    "AgentEvent",
    "dump_agent_message",
    # Agent 循环事件
    "AgentStartEvent",
    "AgentEndEvent",
    "TurnStartEvent",
    "TurnEndEvent",
    "MessageStartEvent",
    "MessageUpdateEvent",
    "MessageEndEvent",
    "ToolExecutionStartEvent",
    "ToolExecutionUpdateEvent",
    "ToolExecutionEndEvent",
    # 流式助手事件
    "AssistantMessageEvent",
    "StartEvent",
    "TextStartEvent",
    "TextDeltaEvent",
    "TextEndEvent",
    "ThinkingStartEvent",
    "ThinkingDeltaEvent",
    "ThinkingEndEvent",
    "ToolCallStartEvent",
    "ToolCallDeltaEvent",
    "ToolCallEndEvent",
    "DoneEvent",
    "ErrorEvent",
    # 兼容性配置
    "AnthropicMessagesCompat",
    "OpenAICompletionsCompat",
    "OpenAIResponsesCompat",
    "OpenRouterRouting",
    "VercelGatewayRouting",
    "SessionAffinityFormat",
    "DeferredToolsMode",
    # 共享别名
    "ProviderEnv",
    "ProviderHeaders",
    # Auth 类型
    "ApiKeyAuth",
    "ApiKeyAuthInput",
    "ApiKeyCredential",
    "AuthCheck",
    "AuthContext",
    "AuthEvent",
    "AuthInfoLink",
    "AuthInteraction",
    "AuthPrompt",
    "AuthPromptOption",
    "AuthResult",
    "AuthType",
    "AuthorizationRequest",
    "Credential",
    "LoginCancelledError",
    "CredentialInfo",
    "CredentialStore",
    "ModelAuth",
    "OAuthAuth",
    "OAuthCredential",
    "ProviderAuth",
]


# ── exec 前置管线词汇（①分析/②裁决——批次 C） ──
from .exec_server_intent import (
    Intent,
    intent_from_argv,
    intent_from_shell,
    extract_bash_command,
    parse_shell_lc_literal_commands,
    parse_shell_script_into_commands,
    DangerousCommandMatch,
    MAX_DANGEROUS_COMMAND_WRAPPER_DEPTH,
    dangerous_command_match,
    executable_name_lookup_key,
    find_git_subcommand,
    is_dangerous_command,
)

from .exec_server_verdict import (
    Decision,
    ExecPolicyAmendment,
    NetworkPolicyRuleAction,
    NetworkPolicyAmendment,
    ExecApprovalRequirement,
    ReviewDecision,
    ReviewDecisionPayload,
    ToolDecisionSource,
)

from .exec_server_policy import (
    PolicyParseError,
    PatternToken,
    PrefixPattern,
    PrefixRule,
    NetworkRuleProtocol,
    normalize_network_rule_host,
    NetworkRule,
    PrefixRuleMatch,
    HeuristicsRuleMatch,
    Evaluation,
    Policy,
    parse_policy,
    format_prefix_rule,
    format_network_rule,
    is_likely_executor_managed_sandbox_denied,
    is_likely_sandbox_denied,
)

# ---------------------------------------------------------------------------
# exec-server 词汇域（批次 A 迁入——线上/配置/环境注册表三类）
# ---------------------------------------------------------------------------
from .exec_server_config import (
    MAX_ENVIRONMENT_ID_LENGTH,
    ApprovalPolicy,
    ExecutorConfig,
    ExecutorEnvironment,
    NetworkProxySettings,
    ResolvedExecutionPolicy,
    SandboxMode,
    SandboxWorkspaceWriteConfig,
)
from .exec_server_environment import (
    LOCAL_ENVIRONMENT_ID,
    ResolvedEnvironment,
)
from .exec_server_wire import (
    ENVIRONMENT_CONFIG_READ,
    ENVIRONMENT_INFO,
    ENVIRONMENT_STATUS,
    FS_CANONICALIZE,
    FS_CLOSE,
    FS_COPY,
    FS_CREATE_DIRECTORY,
    FS_GET_METADATA,
    FS_OPEN,
    FS_READ_BLOCK,
    FS_READ_DIRECTORY,
    FS_READ_FILE,
    FS_READ_STREAM,
    FS_READ_STREAM_CHUNK,
    FS_READ_STREAM_DONE,
    FS_REMOVE,
    FS_WALK,
    FS_WRITE_FILE,
    FS_WRITE_STREAM,
    FS_WRITE_STREAM_CHUNK,
    FS_WRITE_STREAM_DONE,
    HTTP_REQUEST,
    HTTP_REQUEST_BODY_DELTA,
    INITIALIZE,
    INITIALIZED,
    MAX_WRITE_STREAM_CHUNK_BYTES,
    NETWORK_POLICY_DECISION,
    NETWORK_POLICY_REQUEST,
    PROCESS_CLOSED,
    PROCESS_EXITED,
    PROCESS_OUTPUT,
    PROCESS_READ,
    PROCESS_SIGNAL,
    PROCESS_START,
    PROCESS_TERMINATE,
    PROCESS_WRITE,
    PROTOCOL_VERSION,
    ByteChunk,
    DirEntry,
    EnvironmentCapabilities,
    EnvironmentConfigLayer,
    EnvironmentConfigLayerStack,
    EnvironmentConfigReadParams,
    EnvironmentConfigReadResponse,
    EnvironmentInfo,
    EnvironmentStatus,
    ExecEnvPolicy,
    ExecFileSystemPath,
    ExecFileSystemSandboxEntry,
    ExecFileSystemSpecialPath,
    ExecManagedFileSystemPermissions,
    ExecPermissionProfile,
    ExecServerNetworkPolicyRequest,
    ExecServerNetworkProtocol,
    FileMetadata,
    FileSystemAccessMode,
    FileSystemSandboxContext,
    FsCanonicalizeParams,
    FsCanonicalizeResponse,
    FsCloseParams,
    FsCopyParams,
    FsCreateDirectoryParams,
    FsGetMetadataParams,
    FsOpenParams,
    FsOpenResponse,
    FsReadBlockParams,
    FsReadBlockResponse,
    FsReadDirectoryParams,
    FsReadDirectoryResponse,
    FsReadFileParams,
    FsReadFileResponse,
    FsReadStreamChunkNotification,
    FsReadStreamDoneNotification,
    FsReadStreamParams,
    FsReadStreamResponse,
    FsRemoveParams,
    FsWalkParams,
    FsWriteFileParams,
    FsWriteStreamChunkNotification,
    FsWriteStreamDoneParams,
    FsWriteStreamDoneResponse,
    FsWriteStreamParams,
    FsWriteStreamResponse,
    HttpHeader,
    HttpRedirectPolicy,
    HttpRequestBodyDeltaNotification,
    HttpRequestParams,
    HttpRequestResponse,
    InitializeParams,
    InitializeResponse,
    JsonRpcError,
    JsonRpcNotification,
    JsonRpcRequest,
    JsonRpcResponse,
    ManagedNetworkSandboxContext,
    NetworkDomainPermission,
    NetworkDomainPermissionEntry,
    NetworkDomainPermissions,
    NetworkMode,
    NetworkPolicyDecision,
    NetworkPolicyDecisionNotification,
    NetworkPolicyRequestParams,
    NetworkPolicyRequestResponse,
    NetworkProxyAuditMetadata,
    NetworkSandboxPolicy,
    NetworkUnixSocketPermissionEntry,
    NetworkUnixSocketPermissions,
    ProcessExitedNotification,
    ProcessOutputChunk,
    ProcessReadParams,
    ProcessReadResponse,
    ProcessSignalParams,
    ProcessStartParams,
    ProcessStartResponse,
    ProcessTerminateParams,
    ProcessTerminateResponse,
    ProcessWriteParams,
    ProcessWriteResponse,
    RemoteNetworkProxyConfig,
    RemoteNetworkProxyLaunchConfig,
    ShellInfo,
    ShellSnapshotRequest,
    WalkEntry,
    WalkError,
    WalkOptions,
    WalkOutcome,
    WindowsSandboxLevel,
    WindowsSandboxProxySettingsMode,
)
